# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: amalie barras | portfolio | 2017
email: hello@amaliebarras.com
description: > # this means to ignore newlines until "baseurl:"
  amalie barras | UI / UX designer in Boulder, CO
baseurl: "" # the subpath of your site, e.g. /blog
url: "amaliebarras.github.io" # the base hostname & protocol for your site
twitter_username: amaliebarras
github_username:  amaliebarras

# Build settings
markdown: kramdown
